server:
  port: ${SERVER_PORT:8087}
  tomcat:
    min-spare: 25
    max-threads: 750

spring:
  profiles: azure
  application:
    name: ${SPRING_APPLICATION_NAME:voltage-key-cache}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    schema-registry-servers: ${SPRING_KAFKA_SCHEMA_REGISTRY_SERVERS}
    producer:
      value-serializer: ${SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER}
      key-serializer: ${SPRING_KAFKA_PRODUCER_KEY_SERIALIZER}
      acks: ${SPRING_KAFKA_PRODUCER_ACKS}
      batch-size: ${SPRING_KAFKA_PRODUCER_BATCH_SIZE}
      buffer-memory: ${SPRING_KAFKA_PRODUCER_BUFFER_MEMORY}
      linger-ms: ${SPRING_KAFKA_PRODUCER_LINGER_MS}
      max-block-ms: ${SPRING_KAFKA_PRODUCER_MAX_BLOCK_MS}
      retries: ${SPRING_KAFKA_PRODUCER_RETRIES}
    listener:
      ack-mode: ${SPRING_KAFKA_LISTENER_ACK_MODE}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}

management:
  endpoints:
    web:
      exposure:
        include: info,refresh,health,bus-refresh,busrefresh
  endpoint:
    refresh:
      enabled: true

config:
  voltage:
    PolicyUrl: ${CONFIG_VOLTAGE_POLICYURL}
    TrustStorePath: ${CONFIG_VOLTAGE_TRUSTSTOREPATH}
    BasePath: ${CONFIG_VOLTAGE_BASEPATH}
    SharedSecret: ${CONFIG_VOLTAGE_SHAREDSECRET}
    AlphanumericFormat: ${CONFIG_VOLTAGE_ALPHANUMERICFORMAT}
    NumericFormat: ${CONFIG_VOLTAGE_NUMERICFORMAT}
    AlphaFormat: ${CONFIG_VOLTAGE_ALPHAFORMAT}
    ClientId: ${CONFIG_VOLTAGE_CLIENTID}
    ClientIdVersion: ${CONFIG_VOLTAGE_CLIENTIDVERSION}
  datasource:
    KeyDatasource:
      Enabled: ${CONFIG_DATASOURCE_KEYDATASOURCE_ENABLED}
      IdleTimeout: ${CONFIG_DATASOURCE_KEYDATASOURCE_IDLETIMEOUT}
      JdbcUrl: ${CONFIG_DATASOURCE_KEYDATASOURCE_JDBCURL}
      Username: ${CONFIG_DATASOURCE_KEYDATASOURCE_USERNAME}
      Password: ${CONFIG_DATASOURCE_KEYDATASOURCE_PASSWORD}
      MaxLifetime: ${CONFIG_DATASOURCE_KEYDATASOURCE_MAXLIFETIME}
      TestQuery: ${CONFIG_DATASOURCE_KEYDATASOURCE_TESTQUERY}
      MinimumIdle: ${CONFIG_DATASOURCE_KEYDATASOURCE_MINIMUMIDLE}
      DriverClass: ${CONFIG_DATASOURCE_KEYDATASOURCE_DRIVERCLASS}
      PoolName: ${CONFIG_DATASOURCE_KEYDATASOURCE_POOLNAME}
      MaximumPoolSize: ${CONFIG_DATASOURCE_KEYDATASOURCE_MAXIMUMPOOLSIZE}
      AutoCommit: ${CONFIG_DATASOURCE_KEYDATASOURCE_AUTOCOMMIT}
      ConnectionTimeout: ${CONFIG_DATASOURCE_KEYDATASOURCE_CONNECTIONTIMEOUT}
  kafka:
    topic-name-1: ${CONFIG_KAFKA_TOPIC_NAME_1}
    topic-name-2: ${CONFIG_KAFKA_TOPIC_NAME_2}