/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ogya.logging.avro.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class OrderObject extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8482749276253153541L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderObject\",\"namespace\":\"com.ogya.logging.avro.schema\",\"fields\":[{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"username\",\"type\":\"string\"},{\"name\":\"statusId\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OrderObject> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderObject> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OrderObject> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OrderObject> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OrderObject> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OrderObject to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OrderObject from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OrderObject instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OrderObject fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long timestamp;
  private java.lang.CharSequence username;
  private java.lang.CharSequence statusId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderObject() {}

  /**
   * All-args constructor.
   * @param timestamp The new value for timestamp
   * @param username The new value for username
   * @param statusId The new value for statusId
   */
  public OrderObject(java.lang.Long timestamp, java.lang.CharSequence username, java.lang.CharSequence statusId) {
    this.timestamp = timestamp;
    this.username = username;
    this.statusId = statusId;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return timestamp;
    case 1: return username;
    case 2: return statusId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: timestamp = (java.lang.Long)value$; break;
    case 1: username = (java.lang.CharSequence)value$; break;
    case 2: statusId = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'username' field.
   * @return The value of the 'username' field.
   */
  public java.lang.CharSequence getUsername() {
    return username;
  }


  /**
   * Sets the value of the 'username' field.
   * @param value the value to set.
   */
  public void setUsername(java.lang.CharSequence value) {
    this.username = value;
  }

  /**
   * Gets the value of the 'statusId' field.
   * @return The value of the 'statusId' field.
   */
  public java.lang.CharSequence getStatusId() {
    return statusId;
  }


  /**
   * Sets the value of the 'statusId' field.
   * @param value the value to set.
   */
  public void setStatusId(java.lang.CharSequence value) {
    this.statusId = value;
  }

  /**
   * Creates a new OrderObject RecordBuilder.
   * @return A new OrderObject RecordBuilder
   */
  public static com.ogya.logging.avro.schema.OrderObject.Builder newBuilder() {
    return new com.ogya.logging.avro.schema.OrderObject.Builder();
  }

  /**
   * Creates a new OrderObject RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderObject RecordBuilder
   */
  public static com.ogya.logging.avro.schema.OrderObject.Builder newBuilder(com.ogya.logging.avro.schema.OrderObject.Builder other) {
    if (other == null) {
      return new com.ogya.logging.avro.schema.OrderObject.Builder();
    } else {
      return new com.ogya.logging.avro.schema.OrderObject.Builder(other);
    }
  }

  /**
   * Creates a new OrderObject RecordBuilder by copying an existing OrderObject instance.
   * @param other The existing instance to copy.
   * @return A new OrderObject RecordBuilder
   */
  public static com.ogya.logging.avro.schema.OrderObject.Builder newBuilder(com.ogya.logging.avro.schema.OrderObject other) {
    if (other == null) {
      return new com.ogya.logging.avro.schema.OrderObject.Builder();
    } else {
      return new com.ogya.logging.avro.schema.OrderObject.Builder(other);
    }
  }

  /**
   * RecordBuilder for OrderObject instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderObject>
    implements org.apache.avro.data.RecordBuilder<OrderObject> {

    private long timestamp;
    private java.lang.CharSequence username;
    private java.lang.CharSequence statusId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ogya.logging.avro.schema.OrderObject.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[0].schema(), other.timestamp);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.username)) {
        this.username = data().deepCopy(fields()[1].schema(), other.username);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.statusId)) {
        this.statusId = data().deepCopy(fields()[2].schema(), other.statusId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing OrderObject instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ogya.logging.avro.schema.OrderObject other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[0].schema(), other.timestamp);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.username)) {
        this.username = data().deepCopy(fields()[1].schema(), other.username);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.statusId)) {
        this.statusId = data().deepCopy(fields()[2].schema(), other.statusId);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.ogya.logging.avro.schema.OrderObject.Builder setTimestamp(long value) {
      validate(fields()[0], value);
      this.timestamp = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.ogya.logging.avro.schema.OrderObject.Builder clearTimestamp() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'username' field.
      * @return The value.
      */
    public java.lang.CharSequence getUsername() {
      return username;
    }


    /**
      * Sets the value of the 'username' field.
      * @param value The value of 'username'.
      * @return This builder.
      */
    public com.ogya.logging.avro.schema.OrderObject.Builder setUsername(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.username = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'username' field has been set.
      * @return True if the 'username' field has been set, false otherwise.
      */
    public boolean hasUsername() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'username' field.
      * @return This builder.
      */
    public com.ogya.logging.avro.schema.OrderObject.Builder clearUsername() {
      username = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'statusId' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatusId() {
      return statusId;
    }


    /**
      * Sets the value of the 'statusId' field.
      * @param value The value of 'statusId'.
      * @return This builder.
      */
    public com.ogya.logging.avro.schema.OrderObject.Builder setStatusId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.statusId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'statusId' field has been set.
      * @return True if the 'statusId' field has been set, false otherwise.
      */
    public boolean hasStatusId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'statusId' field.
      * @return This builder.
      */
    public com.ogya.logging.avro.schema.OrderObject.Builder clearStatusId() {
      statusId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderObject build() {
      try {
        OrderObject record = new OrderObject();
        record.timestamp = fieldSetFlags()[0] ? this.timestamp : (java.lang.Long) defaultValue(fields()[0]);
        record.username = fieldSetFlags()[1] ? this.username : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.statusId = fieldSetFlags()[2] ? this.statusId : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderObject>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderObject>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderObject>
    READER$ = (org.apache.avro.io.DatumReader<OrderObject>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.timestamp);

    out.writeString(this.username);

    out.writeString(this.statusId);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.timestamp = in.readLong();

      this.username = in.readString(this.username instanceof Utf8 ? (Utf8)this.username : null);

      this.statusId = in.readString(this.statusId instanceof Utf8 ? (Utf8)this.statusId : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.timestamp = in.readLong();
          break;

        case 1:
          this.username = in.readString(this.username instanceof Utf8 ? (Utf8)this.username : null);
          break;

        case 2:
          this.statusId = in.readString(this.statusId instanceof Utf8 ? (Utf8)this.statusId : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










